<a href="https://colab.research.google.com/github/tjdrms0930/bit2210_bigdata/blob/main/Colaboratory%EC%97%90_%EC%98%A4%EC%8B%A0_%EA%B2%83%EC%9D%84_%ED%99%98%EC%98%81%ED%95%A9%EB%8B%88%EB%8B%A4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

https://numpy.org/

In [14]:
#numpy 모듈을 사용하기 위한 import문
import numpy as np

In [5]:
ls= [1,2,3,4,5]
arr = np.array(ls)
print(arr)
print(type(arr)) #다차원

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [6]:
ls1 = [1,2,3]
ls2 = [4,7,2]
ls3 = ls1+ls2
print(ls3) #파이썬 리스트의 합은 concat

[1, 2, 3, 4, 7, 2]


In [8]:
arr1 = np.array(ls1)
arr2 = np.array(ls2)
arr3 = arr1 + arr2
print(arr3) #numpy의 + 연산은 행렬의 + 연산을 수행 

[5 9 5]


In [9]:
ls=[1,2,3]
ls2 = ls*3
print(ls2) #리스트 *수는 반복해서 나열 

[1, 2, 3, 1, 2, 3, 1, 2, 3]


In [10]:
arr = np.array(ls)
arr2 = arr*3
print(arr2) #numpy의 ndarray*정수는 행렬 *정수 연산을 수행

[3 6 9]


%%time을 마킹하면 수행 시간을 측정해 줍니다.

In [11]:
%%time 
#수행한 시간확인 가능, numpy 수행속도가 더 빠름.
arr = np.arange(100000)

[1 2 3]
CPU times: user 2.78 ms, sys: 0 ns, total: 2.78 ms
Wall time: 2.64 ms


In [12]:
%%time
ls = list(range(100000))

CPU times: user 1.3 ms, sys: 3.18 ms, total: 4.49 ms
Wall time: 4.49 ms


In [16]:
arr = np.random.randn(2,3) #2X3 행렬을 생성(원소는 랜덤하게 결정)
print(arr)

[[ 0.68082259 -0.94806296 -0.92574233]
 [-0.18553552  1.16087171  1.62283753]]


In [20]:
# arr*3  #값이 바뀐거지 arr이 바뀐것이 아니다. 주의!
arr2 = arr*3
arr2

array([[ 2.04246777, -2.84418887, -2.77722698],
       [-0.55660655,  3.48261512,  4.86851259]])

In [18]:
arr

array([[ 0.68082259, -0.94806296, -0.92574233],
       [-0.18553552,  1.16087171,  1.62283753]])

In [21]:
arr.shape #구조 확인

(2, 3)

In [22]:
arr.ndim #차원 확인

2

In [23]:
arr.dtype #원소 타입 확인

dtype('float64')

In [25]:
arr = np.array([1,2,3])
print(arr)
print(arr.dtype)

[1 2 3]
int64


In [30]:
arr = np.array([1,2,3,4.2]) #정수와 실수로 배열 생성 => 모든 정수는 실수로 변환
print(arr)
print(arr.dtype)
print(type(arr[0])) #numpy 배열에서는 모든 원소가 같은 형식으로 되어있음.

[1.  2.  3.  4.2]
float64
<class 'numpy.float64'>


In [31]:
arr = np.array([1,2,3,4.2,'a']) #수와 문자열로 배열 생성 => 모두 문자열로 변환
print(arr)
print(arr.dtype)
print(type(arr[0])) #numpy 배열에서는 모든 원소가 같은 형식으로 되어있음.

['1' '2' '3' '4.2' 'a']
<U32
<class 'numpy.str_'>


다차원 배열 생성

In [33]:
ls = [1,2,3]
arr = np.array(ls) #리스트를 입력 인자로 ndarray 개체 생성
print(arr)
print(type(arr))

[1 2 3]
<class 'numpy.ndarray'>


In [34]:
ls = [[1,2,3],[2,5,6]]
arr = np.array(ls) #리스트를 입력 인자로 ndarray 개체 생성
print(arr)
print(type(arr))

[[1 2 3]
 [2 5 6]]
<class 'numpy.ndarray'>


In [39]:
arr = np.zeros(10)
print(arr)
print("구조:",arr.shape)
print("차원:",arr.ndim)
print("원소 형식:",arr.dtype)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
구조: (10,)
차원: 1
원소 형식: float64


In [40]:
arr = np.zeros((3,6))
print(arr)
print("구조:",arr.shape)
print("차원:",arr.ndim)
print("원소 형식:",arr.dtype)

[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]
구조: (3, 6)
차원: 2
원소 형식: float64


In [41]:
arr = np.ones((3,6))
print(arr)
print("구조:",arr.shape)
print("차원:",arr.ndim)
print("원소 형식:",arr.dtype)

[[1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]]
구조: (3, 6)
차원: 2
원소 형식: float64


In [42]:
arr = np.arange(20)
print(arr)
print("구조:",arr.shape)
print("차원:",arr.ndim)
print("원소 형식:",arr.dtype)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
구조: (20,)
차원: 1
원소 형식: int64


In [43]:
arr = np.arange(3,20,4)
print(arr)
print("구조:",arr.shape)
print("차원:",arr.ndim)
print("원소 형식:",arr.dtype)

[ 3  7 11 15 19]
구조: (5,)
차원: 1
원소 형식: int64


원소 타입

In [44]:
arr = np.array([1,2,3])
print(type(arr[0]), type(arr[1]), type(arr[2]))
print(arr.dtype)

<class 'numpy.int64'> <class 'numpy.int64'> <class 'numpy.int64'>
int64


In [46]:
arr = np.array([1,2,4.2],dtype=np.int32) #dytpe 인자를 이용하여 명시적으로 원소 형식 결정
print(type(arr[0]), type(arr[1]), type(arr[2]))
print(arr.dtype)
print(arr)

<class 'numpy.int32'> <class 'numpy.int32'> <class 'numpy.int32'>
int32
[1 2 4]


산술 연산

In [48]:
arr = np.array([[1,2,3],[4,5,6]])
print(arr)
print("===============")
arr2 = arr * arr
print(arr2)

[[1 2 3]
 [4 5 6]]
[[ 1  4  9]
 [16 25 36]]


In [49]:
arr2 = arr-arr
print(arr2)

[[0 0 0]
 [0 0 0]]


In [50]:
arr2 = 1/arr
print(arr2)

[[1.         0.5        0.33333333]
 [0.25       0.2        0.16666667]]


In [51]:
arr2 = arr**0.5
print(arr2)

[[1.         1.41421356 1.73205081]
 [2.         2.23606798 2.44948974]]


In [52]:
arr1 = np.array([1,2,3]) # 같은 행끼리 비교해서 > , < 비교 -> True,False 
arr2 = np.array([4,0,2])
fillter = arr1>arr2
print(fillter)

[False  True  True]


색인 및 슬라이싱

In [53]:
arr = np.arange(10000)

In [54]:
print(arr[5:8])

[5 6 7]


In [55]:
print(arr[:8])

[0 1 2 3 4 5 6 7]


In [57]:
print(arr[995:])

[ 995  996  997 ... 9997 9998 9999]


In [58]:
print(arr[-5:])

[9995 9996 9997 9998 9999]


In [59]:
arr = np.zeros(30)
print(arr)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0.]


In [60]:
arr[5:8] = 7
print(arr) #브로드캐스팅 가능 

[0. 0. 0. 0. 0. 7. 7. 7. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0.]


In [61]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [63]:
print(arr[0])
print(arr[1])
print(arr[2])

[1 2 3]
[4 5 6]
[7 8 9]


In [64]:
print(arr[0][2])

3


In [65]:
print(arr[0,2])

3


In [69]:
#소스 배열을 가지고 간단한 실험을 하기 위해서 복사하여 사용하기
cp_arr = arr.copy()
print(cp_arr)
cp_arr[0][1]=8
print(cp_arr)
print(arr)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 8 3]
 [4 5 6]
 [7 8 9]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [70]:
cp_arr = arr # arr과 cp_arr은 같은 개체를 참조
print(cp_arr)
cp_arr[0][1]=8
print(cp_arr)
print(arr)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 8 3]
 [4 5 6]
 [7 8 9]]
[[1 8 3]
 [4 5 6]
 [7 8 9]]


In [71]:
arr = np.array([1,2,3])

fillter = arr>=2 #평균치를 구한 후 비교
print(fillter)

[False  True  True]


In [72]:
res = arr[fillter]
print(res)

[2 3]


In [73]:
res = arr[~fillter]
print(res)

[1]


구조 변경

In [74]:
arr = np.arange(96)
print("구조:", arr.shape)
print("차원:", arr.ndim)

구조: (96,)
차원: 1


In [76]:
arr2 = arr.reshape((6,16))
print("구조:", arr2.shape)
print("차원:", arr2.ndim)

구조: (6, 16)
차원: 2


In [77]:
#arr2 = arr.reshape((7,14))  # 7 * n 이 96이 아니라서 오류
#print("구조:", arr2.shape)
#print("차원:", arr2.ndim)

ValueError: ignored

In [78]:
arr2 = arr.reshape((6, -1)) # 구조 변경 요청할 때 하나의 차원은 -1로 표현 가능(알아서 계산)
print("구조:", arr2.shape)
print("차원:", arr2.ndim)

구조: (6, 16)
차원: 2


In [79]:
arr = np.array([[1,2,3],[4,5,6]]) 
arr2 = arr.T #전치 행렬
print(arr)
print("=========")
print(arr2)

[[1 2 3]
 [4 5 6]]
[[1 4]
 [2 5]
 [3 6]]


In [80]:
arr2 = arr.transpose() #arr.T와 arr.transpose()는 같은 결과(전치행렬)를 반환한다.
print(arr)
print("=========")
print(arr2)

[[1 2 3]
 [4 5 6]]
[[1 4]
 [2 5]
 [3 6]]


In [81]:
arr = np.arange(10)
print(arr)

[0 1 2 3 4 5 6 7 8 9]


In [82]:
arr2 = np.sqrt(arr)
print(arr2)
print(arr)

[0.         1.         1.41421356 1.73205081 2.         2.23606798
 2.44948974 2.64575131 2.82842712 3.        ]
[0 1 2 3 4 5 6 7 8 9]


In [86]:
arr1 = np.random.randn(2,3)
print(arr1)
print("===========================================")
arr2 = np.random.randn(2,3)
print(arr2)

[[-0.35193413  0.89178704  0.1987887 ]
 [ 1.70436815  1.9071598   1.88783091]]
[[-0.88450659  0.20528611 -0.52951536]
 [-0.88891234  1.59624974 -0.78934137]]


In [84]:
arr3 = np.maximum(arr1, arr2)
print(arr3)

[[ 1.04025366 -0.86793055 -0.46002979]
 [ 2.01655676 -0.01304051  1.84969505]]


# Numpy 안으로

In [87]:
# 잠시 파이썬 기본 문법 - 리스트 컴프리헨션
xs = [x*x+2*x+3 for x in range(1, 10)] #리스트 컴프리헨션
print(xs)

[6, 11, 18, 27, 38, 51, 66, 83, 102]


In [88]:
xs=[]
for x in range(1,10):
   xs.append(x*x+2*x+3)
print(xs) # 위 코드와 동일

[6, 11, 18, 27, 38, 51, 66, 83, 102]


In [90]:
xarr = np.array([1.1,1.2,1.3,1.4,1.5])
yarr = np.array([2.1,2.2,2.3,2.4,2.5])
cond = np.array([True,False,True,True,False])

In [91]:
# 파이썬 기초 문법 - zip 사용 예
ls1=[1,2,3]
ls2 = ['가','나','다']
for e1, e2 in zip(ls1,ls2):
  print(e1,e2)

1 가
2 나
3 다


In [92]:
result = [(x if c else y) for x,y,c in zip(xarr,yarr,cond)]
print(result)

[1.1, 2.2, 1.3, 1.4, 2.5]


In [93]:
result=[]
for x,y,c in zip(xarr,yarr,cond):
  if c:
    result.append(x)
  else:
    result.append(y)
print(result)

[1.1, 2.2, 1.3, 1.4, 2.5]


In [94]:
result = np.where(cond,xarr,yarr)
print(result)

[1.1 2.2 1.3 1.4 2.5]


In [95]:
result = np.where(cond,1,2)
print(result)

[1 2 1 1 2]


In [98]:
heights = np.random.normal(172.4,5,1000) #평균 172.4 표준편차 5인 표본 1000개를 생성
print(heights)

[172.1828437  175.16908892 171.64938393 169.05531831 170.15934791
 168.83038603 179.20196726 174.23606754 167.51905957 176.79321281
 174.47036543 170.44188065 175.20198554 170.29732769 168.16662516
 172.61443777 167.8009188  173.20855897 177.49788736 179.38352791
 169.90844117 170.13904557 172.0124249  178.7948107  176.91295723
 174.73317673 174.53110589 175.76014408 170.5846333  172.64143221
 164.89091528 173.19926671 171.46693324 168.79028807 164.1347969
 169.27765155 172.42570095 172.14520998 157.98333641 175.41676203
 171.45580389 181.61591346 176.7548849  173.98801907 172.96054544
 176.18582371 174.31214874 178.74801015 163.25526686 170.74736354
 173.88186842 167.401951   175.92678212 175.94482669 176.33226683
 170.72546349 171.80182746 174.10710991 176.34132722 178.64196786
 161.27442938 164.88445307 179.86615988 170.64807595 177.7567128
 172.02809738 168.47670717 179.72110667 159.60224377 176.09740854
 175.51243932 174.12555307 173.86688805 171.78405838 176.61758187
 175.6937062

In [101]:
print("평균:", heights.mean()) #print("평균:", np.mean(heights))
print("합계:", heights.sum()) #print("평균:", np.sum(heights))

평균: 172.69548420763678
합계: 172695.4842076368


In [ ]:
h2 = heights.reshape(20,-1)
print("구조:", h2.shape)
print(h2)

In [106]:
print("평균(축0):", h2.mean(axis=0)) #컬럼 별 평균
print("평균(축1):", h2.mean(axis=1)) #로우 별 평균

평균(축0): [172.86792325 172.79446524 171.65999972 173.39185967 171.50807322
 173.61341526 173.58792549 172.20008839 174.37457835 173.20984817
 172.40562874 172.19671338 174.42246175 173.64543604 173.45696419
 172.14244226 171.48092779 174.32366216 173.26180984 172.56494318
 170.78594912 172.04172879 172.30407833 172.2235126  171.72491124
 172.90541279 170.41574378 171.39005415 171.19295533 172.92201254
 172.30109814 172.24246356 173.3891519  173.49539729 173.18295387
 172.80218419 173.04348322 172.76622898 173.06398529 174.71304563
 172.83646138 175.29418991 172.86333953 172.49485477 172.28830543
 172.22049074 172.82623189 169.64121562 171.44450347 174.84910085]
평균(축1): [172.39306008 172.37735016 171.96166537 171.95778466 171.52916922
 173.42024293 172.54461863 173.56183658 173.22344325 172.21594147
 172.7101196  173.32028407 172.56549792 173.35099464 173.1576501
 173.33164645 172.73193548 171.71785119 172.93992737 172.89866498]


In [108]:
print("합계(축0):", h2.sum(axis=0)) #컬럼 별 합계
print("합계(축1):", h2.sum(axis=1)) #로우 별 합계

합계(축0): [3457.358465   3455.88930482 3433.19999432 3467.83719347 3430.16146446
 3472.26830516 3471.75850982 3444.00176775 3487.49156696 3464.19696341
 3448.11257481 3443.9342677  3488.44923498 3472.90872079 3469.13928385
 3442.84884511 3429.61855587 3486.47324318 3465.23619673 3451.29886353
 3415.71898241 3440.83457584 3446.0815666  3444.47025192 3434.49822486
 3458.10825575 3408.31487551 3427.80108301 3423.85910655 3458.44025081
 3446.02196282 3444.84927126 3467.7830379  3469.90794573 3463.65907731
 3456.04368371 3460.86966432 3455.32457957 3461.27970577 3494.26091262
 3456.72922753 3505.8837983  3457.26679051 3449.89709532 3445.76610867
 3444.40981489 3456.52463776 3392.82431231 3428.89006944 3496.98201691]
합계(축1): [8619.65300391 8618.86750788 8598.08326825 8597.88923314 8576.45846107
 8671.01214647 8627.23093132 8678.09182916 8661.17216234 8610.7970737
 8635.50598002 8666.01420359 8628.27489623 8667.54973181 8657.88250481
 8666.58232234 8636.59677419 8585.89255962 8646.9963686  8644

In [107]:
print("분산:", h2.var())
print("표준편차:", h2.std())

분산: 23.72627961068828
표준편차: 4.87096290385056


In [109]:
print("최솟값:", h2.min())
print("최댓값:", h2.max())

최솟값: 156.92781223520427
최댓값: 186.69517438953233


In [111]:
print("최솟값이 있는 위치:", h2.argmin())
print("최댓값이 있는 위치:", h2.argmax())
print(heights[heights.argmin()], heights[heights.argmax()])

최솟값이 있는 위치: 947
최댓값이 있는 위치: 555
156.92781223520427 186.69517438953233


In [113]:
arr = np.array([1,2,4,2,7])
print("누적 합계:", arr.cumsum())
print("누적 곱:", arr.cumprod())

누적 합계: [ 1  3  7  9 16]
누적 곱: [  1   2   8  16 112]


In [114]:
arr.sort()
print(arr)

[1 2 2 4 7]


In [115]:
ua = np.unique(arr) #도수 조사 // 이 배열에 어떠한 요소들이 있는지 -> 중복제외
print(ua)

[1 2 4 7]


In [118]:
x = np.array([[1,2,3],[4,5,6]])
y = np.array([[2,3],[1,2],[4,5]])
re = x.dot(y)
print(x)
print("============")
print(y)
print("============")
print(re)

[[1 2 3]
 [4 5 6]]
[[2 3]
 [1 2]
 [4 5]]
[[16 22]
 [37 52]]


# 난수


In [120]:
for _ in range(10): # _ 변수 이름을 주지 않겠다.
  print(np.random.uniform(-2,3)) # -2 ~ 3사이에 랜덤한 실수 반환

2.0540317130891204
-1.0041756915850868
-0.1606603149711905
1.6997953424481311
0.08062328912296435
1.0408658397021675
2.6408137707344705
1.1910808943873796
1.1429830544515394
1.054034007297421


In [125]:
for _ in range(20):
  print(np.random.randint(1,7), end=' ') # 1에서 5사이의 랜덤한 정수 반환
print()

4 5 1 3 5 4 1 4 4 1 2 2 2 6 1 5 1 2 6 2 


In [134]:
volan = [1,7,2,8,9]
for _ in range(20):
  print(np.random.choice(volan), end=' ') # 저 숫자중에 랜덤하게 아무거나 골라라
print()

2 1 7 9 7 8 9 9 2 1 8 7 9 2 1 9 7 7 2 9 


In [135]:
np.random.seed(100)